spring:
  datasource:
    url: localhost:3306/dreamshop_db
    username: root
    password: password
    driver-class-name: org.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
    hibernate:
      ddl-auto: update
